apiVersion: v1
kind: Secret
metadata:
  name: tcs-overlay
type: Opaque
stringData:
  overlay.yaml: |
    #@ load("@ytt:overlay", "overlay")
    #@overlay/match by=overlay.subset({"kind":"ConfigMap", "metadata": {"name":"istio","namespace":"istio-system"}}), expects=1
    ---
    data:
      mesh: |-
       enableTracing: true
       defaultConfig:
         discoveryAddress: istiod.istio-system.svc:15012
         proxyMetadata:
           ISTIO_META_DNS_AUTO_ALLOCATE: "true"
         tracing:
           zipkin:
             address: zipkin.istio-system:9411
       defaultProviders:
         metrics:
         - prometheus
       enablePrometheusMerge: true
       outboundTrafficPolicy:
         mode: ALLOW_ANY
       rootNamespace: istio-system
       trustDomain: cluster.local
